name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab=4.0.11
  - seaborn=0.12.2
  - pandas=2.2.0
  - pip=23.3.1
  - ydata-profiling=4.6.4
  - pyarrow=14.0.2
  - ipywidgets=8.1.1
  - pip:
      - wandb==0.16.2
