name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.0
  - pytest=8.0.0
  - scipy=1.11.4
  - pip=24.0
  - pip:
      - mlflow==2.10.0
      - wandb==0.16.2
