name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.4.0
  - pandas=2.2.0
  - pip:
      - mlflow==2.10.0
      - wandb==0.16.2
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
