name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.2.0
  - pip=23.3.1
  - scikit-learn=1.4.0
  - pip:
      - mlflow==2.10.0
      - wandb==0.16.2
