name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - requests=2.24.0
  - pip:
      - mlflow==2.10.0
      - wandb==0.16.2
      - git+https://github.com/dbaeza0/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
